sudo: required

services:
  - docker
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE eh_testing;'
  - docker build -t agamblin/eh-server-test -f ./Dockerfile.dev .

script:
  - docker run --net=host -e AWS_ACCESS_KEY=$S3_AWS_ACCESS_KEY -e AWS_SECRET_KEY=$S3_AWS_SECRET_KEY -e AWS_BUCKET_NAME=$S3_AWS_BUCKET_NAME -e SQL_HOST=127.0.0.1 -e SQL_PORT=3306 -e SQL_USER=root -e SQL_PASSWORD='' -e SQL_DB=eh_testing -e NODE_ENV=CI -e JWT_SECRET=somejwtrandom agamblin/eh-server-test yarn launch-tests --coverage
